In [3]:
import torch

In [4]:
x=torch.tensor(3.0,requires_grad=True)

In [5]:
y=x**2

In [6]:
x

tensor(3., requires_grad=True)

In [7]:
y

tensor(9., grad_fn=<PowBackward0>)

In [8]:
y.backward()

In [9]:
x.grad

tensor(6.)

In [10]:
import math
def dz_dx(x):
    return 2*x*math.cos(x**2)


In [11]:
dz_dx(3)

-5.466781571308061

In [26]:
x=torch.tensor(7.0,requires_grad=True)

In [27]:
y=x**2

In [28]:
z=torch.sin(y)

In [29]:
z

tensor(-0.9538, grad_fn=<SinBackward0>)

In [30]:
z.backward()

In [31]:
x.grad

tensor(4.2083)

In [32]:
y.grad

/tmp/ipython-input-486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [33]:
import torch

In [34]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [35]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [36]:
z=w*x+b

In [38]:
y_pred=torch.sigmoid(z)

In [43]:
loss=-((y*torch.log(y_pred)+(1-y)*(torch.log(1-y_pred))))

In [44]:
loss.backward()

In [45]:
w.grad

tensor(6.6918)

In [46]:
b.grad

tensor(0.9988)

In [61]:
arr=torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True)

In [62]:
arr

tensor([1., 2., 3.], requires_grad=True)

In [63]:
y=(arr**2).mean()

In [64]:
y.backward()

In [65]:
arr.grad

tensor([0.6667, 1.3333, 2.0000])

In [68]:
arr.grad.zero_()

tensor([0., 0., 0.])

In [79]:
x=torch.tensor(3.0,requires_grad=True)

In [83]:
x.requires_grad_(False)

tensor(3.)

In [84]:
t=x**2

In [85]:
t

tensor(9.)

In [87]:
#detach
x=torch.tensor(3.0,requires_grad=True)

In [88]:
z=x.detach()

In [89]:
z

tensor(3.)

In [90]:
#.no_grad()
x=torch.tensor(3.0,requires_grad=True)

In [92]:
with torch.no_grad():
    y=x**2

In [ ]:
y.backward()

In [94]:
y

tensor(9.)