In [2]:
import torch
from sklearn.datasets import make_classification

In [6]:
X,y=make_classification(
    n_samples=100,
    n_features=2,
    n_classes=2,
    n_clusters_per_class=1,
    n_informative=1,
    n_redundant=1,
    random_state=230
)

In [8]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [13]:
#dataset and Dataloader
from torch.utils.data import Dataset,DataLoader

In [22]:
from sklearn.preprocessing import StandardScaler

In [14]:
class CustomDataset(Dataset):
    def __init__(self,X,y):
        self.X=X
        self.y=y
    def __len__(self):
        return self.X.shape[0]
    def __getitem__(self,index):

        return self.X[index],self.y[index]

In [15]:
dataset=CustomDataset(X,y)

In [17]:
len(dataset)

100

In [18]:
dataset[3]

(tensor([ 0.5731, -0.2091]), tensor(1))

In [25]:
dataloader=DataLoader(dataset,batch_size=10,shuffle=True,num_workers=2)

In [26]:
for X_batch,y_batch in dataloader:
    print(X_batch)
    print(y_batch)
    print("-"*50)

tensor([[ 1.6460, -0.6006],
        [-0.9935,  0.3625],
        [-1.0422,  0.3803],
        [ 1.2973, -0.4734],
        [-0.9746,  0.3556],
        [-1.0328,  0.3769],
        [ 1.8435, -0.6727],
        [ 0.4467, -0.1630],
        [ 1.3724, -0.5008],
        [ 1.2550, -0.4580]])
tensor([1, 0, 0, 1, 0, 0, 1, 1, 1, 1])
--------------------------------------------------
tensor([[ 0.3519, -0.1284],
        [ 0.8850, -0.3229],
        [ 0.4692, -0.1712],
        [-1.0031,  0.3660],
        [-1.0191,  0.3719],
        [-0.9322,  0.3402],
        [ 0.3762, -0.1373],
        [-1.0348,  0.3776],
        [-1.0170,  0.3711],
        [ 1.6822, -0.6138]])
tensor([1, 1, 1, 0, 0, 0, 1, 0, 0, 1])
--------------------------------------------------
tensor([[-1.0052,  0.3668],
        [ 2.0946, -0.7643],
        [ 0.5364, -0.1957],
        [-1.0014,  0.3654],
        [-0.9835,  0.3589],
        [ 0.9934, -0.3625],
        [ 0.5731, -0.2091],
        [-1.0184,  0.3716],
        [ 0.7523, -0.2745],
      

In [27]:
import kagglehub
path=kagglehub.dataset_download("yasserh/breast-cancer-dataset")

100%|██████████| 48.6k/48.6k [00:00<00:00, 2.66MB/s]

Extracting files...


In [28]:
import os
os.listdir(path)

['breast-cancer.csv']

In [29]:
import pandas as pd

In [30]:
df=pd.read_csv(path+"/breast-cancer.csv")

In [31]:
df

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
..        ...       ...  ...             ...                      ...
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]

In [32]:
df.drop("id",inplace=True,axis=1)

In [33]:
X=df.drop("diagnosis",axis=1)
y=df["diagnosis"]

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [35]:
scaler=StandardScaler()
encoder=LabelEncoder()
X_=scaler.fit_transform(X)
y_=encoder.fit_transform(y)

In [38]:
x_train,x_test,y_train,y_test=train_test_split(X_,y_,test_size=0.2)

In [41]:
x_train_torch=torch.tensor(x_train,dtype=torch.float32)
x_test_torch=torch.tensor(x_test,dtype=torch.float32)
y_train_torch=torch.tensor(y_train,dtype=torch.long)
y_test_torch=torch.tensor(y_test,dtype=torch.long)

In [56]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
    def __init__(self,X,y):
        self.X=X
        self.y=y
    def __len__(self):
        return self.X.shape[0]
    def __getitem__(self,index):
        return self.X[index],self.y[index]

In [46]:
import torch.nn as nn
class MyNN(nn.Module):
    def __init__(self,n_features):
        super().__init__()
        self.n_features=n_features
        self.linear=nn.Linear(n_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,X):
        out=self.linear(X)
        out=self.sigmoid(out)
        return out

In [60]:
learning_rate=0.1
loss_function=nn.BCELoss()
epochs=10

In [49]:
from torch.optim import SGD


In [54]:
model=MyNN(x_train_torch.shape[1])
optimizer=SGD(model.parameters(),lr=learning_rate)

In [57]:
train_dataset=CustomDataset(x_train_torch,y_train_torch)
test_dataset=CustomDataset(x_test_torch,y_test_torch)

In [58]:
train_dataloader=DataLoader(train_dataset,batch_size=30,shuffle=True)
test_dataloader=DataLoader(test_dataset,batch_size=30,shuffle=True)

In [ ]:
for epoch in range(epochs):
    for x,y in train_dataloader:
        y_pred=model(x)
        y_pred=y_pred.to(torch.float32)
        y=y.to(torch.float32)
        loss=loss_function(y_pred,y.view(-1,1))

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        print(loss)


In [69]:
accuracy_list=[]
with torch.no_grad():
    for x_tes,y_tes in test_dataloader:
        y_pred=model.forward(x_tes)
        y_pred=(y_pred>0.8).float()

        batch_accuracy=(y_pred.view(-1)==y_tes).float().mean().item()
        accuracy_list.append(batch_accuracy)



In [75]:
print(f"accuarcy=={sum(accuracy_list)/4:.2f}")

accuarcy==0.93
