In [1]:
#introduction to pytouch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
  print("gpu available")
  print("using gpa ",torch.cuda.get_device_name(0))
else:
  print("gpu not available: using CPU")

gpu not available: using CPU


### using tensor

In [4]:
#using empty
a=torch.empty(2,7)

In [5]:
#type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(9,9)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(3,2)

tensor([[0.2636, 0.3788],
        [0.0775, 0.0380],
        [0.0801, 0.8759]])

In [9]:
torch.rand(3,2)

tensor([[0.5347, 0.8917],
        [0.4692, 0.5382],
        [0.5849, 0.8535]])

In [10]:
torch.manual_seed(200)
torch.rand(2,3)

tensor([[0.5939, 0.5008, 0.9961],
        [0.0311, 0.1716, 0.9481]])

In [11]:
torch.manual_seed(200)
torch.rand(2,3)

tensor([[0.5939, 0.5008, 0.9961],
        [0.0311, 0.1716, 0.9481]])

In [12]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [13]:
torch.arange(0,29,3)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [15]:
torch.linspace(0,1000,100)

tensor([   0.0000,   10.1010,   20.2020,   30.3030,   40.4040,   50.5051,
          60.6061,   70.7071,   80.8081,   90.9091,  101.0101,  111.1111,
         121.2121,  131.3131,  141.4141,  151.5152,  161.6162,  171.7172,
         181.8182,  191.9192,  202.0202,  212.1212,  222.2222,  232.3232,
         242.4243,  252.5253,  262.6263,  272.7273,  282.8283,  292.9293,
         303.0303,  313.1313,  323.2323,  333.3333,  343.4344,  353.5354,
         363.6364,  373.7374,  383.8384,  393.9394,  404.0404,  414.1414,
         424.2424,  434.3434,  444.4445,  454.5455,  464.6465,  474.7475,
         484.8485,  494.9495,  505.0505,  515.1515,  525.2525,  535.3535,
         545.4545,  555.5555,  565.6566,  575.7576,  585.8586,  595.9596,
         606.0606,  616.1616,  626.2626,  636.3636,  646.4647,  656.5657,
         666.6667,  676.7677,  686.8687,  696.9697,  707.0707,  717.1717,
         727.2727,  737.3737,  747.4747,  757.5757,  767.6768,  777.7778,
         787.8788,  797.9798,  808.080

In [16]:
torch.full((9,9),9)

tensor([[9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [17]:
x=torch.tensor([[2,4,5],[4,5,6]])

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[136054372097408, 136054372097408,        11662568],
        [136052924406864, 136054340385712,        11665392]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.6470, 0.9265, 0.6200],
        [0.3349, 0.7323, 0.7349]])

In [26]:
x.dtype

torch.int64

In [29]:
y=torch.tensor([1,2,3],dtype=torch.float64)

In [30]:
y

tensor([1., 2., 3.], dtype=torch.float64)

In [33]:
y.to(torch.int)

tensor([1, 2, 3], dtype=torch.int32)

In [46]:
torch.manual_seed(100)
x=torch.rand(2,2)

In [47]:
#addition
x+3
#subtraction
x-3
#division
(x*100)/4
#multiply
x*3
# int division
(x*100)//3
#mod
((x*100)//3)%2
x**30

tensor([[2.7380e-29, 2.2295e-03],
        [3.7753e-18, 3.4839e-10]])

In [58]:
a=torch.tensor([[3,4],[5,6]],dtype=torch.float32)
b=torch.tensor([[1,2],[1,3]])

In [53]:
#addition
a/ b

tensor([[3., 2.],
        [5., 2.]])

In [56]:
torch.sum(a,dim=0)

tensor([ 8, 10])

In [65]:
torch.argmax(a)

tensor(3)

In [89]:
f=torch.randint(size=(3,2),low=2,high=10,dtype=torch.float32)
g=torch.randint(size=(3,2),low=2,high=10,dtype=torch.float32)

In [70]:
torch.matmul(f,g)

tensor([[ 50.,  91.],
        [ 52., 100.]])

In [71]:
torch.transpose(f,0,1)

tensor([[4., 4.],
        [7., 8.],
        [4., 4.]])

In [75]:
torch.det(f)

tensor(38.0000)

In [76]:
torch.inverse(f)

tensor([[-0.3421, -0.3158,  0.5789],
        [ 0.8158,  0.3684, -0.8421],
        [-0.1053,  0.2105, -0.0526]])

In [79]:
f<g

tensor([[ True, False],
        [ True, False],
        [ True,  True]])

In [90]:
torch.log(f)

tensor([[2.1972, 2.1972],
        [1.6094, 0.6931],
        [1.3863, 1.0986]])

In [91]:
torch.exp(f)

tensor([[8.1031e+03, 8.1031e+03],
        [1.4841e+02, 7.3891e+00],
        [5.4598e+01, 2.0086e+01]])

In [92]:
torch.sqrt(f)

tensor([[3.0000, 3.0000],
        [2.2361, 1.4142],
        [2.0000, 1.7321]])

In [93]:
torch.sigmoid(f)

tensor([[0.9999, 0.9999],
        [0.9933, 0.8808],
        [0.9820, 0.9526]])

In [94]:
torch.softmax(f,dim=0)

tensor([[9.7556e-01, 9.9662e-01],
        [1.7868e-02, 9.0880e-04],
        [6.5733e-03, 2.4704e-03]])

In [95]:
torch.relu(f)

tensor([[9., 9.],
        [5., 2.],
        [4., 3.]])

In [96]:
k=torch.randint(size=(3,2),low=2,high=10,dtype=torch.float32)
n=torch.randint(size=(3,2),low=2,high=10,dtype=torch.float32)

In [97]:
k.add_(n)

tensor([[14., 11.],
        [15., 11.],
        [14.,  6.]])

In [98]:
k

tensor([[14., 11.],
        [15., 11.],
        [14.,  6.]])

In [99]:
s=k.clone()

In [101]:
id(s)

136052789811456

In [102]:
id(k)

136052790151040

## Tensor Operations on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
dev=torch.device("cuda")

In [6]:
a=torch.tensor([1,2,3],device=dev)

In [7]:
a

tensor([1, 2, 3], device='cuda:0')

In [8]:
#cpu vs GPU
import time
size=10000
cpu1=torch.rand(size,size)
cpu2=torch.rand(size,size)

start=time.time()
torch.matmul(cpu1,cpu2)
last=time.time()
print(f"cpu time : {last-start:.2f}")

cpu1=torch.rand(size,size,device=dev)
cpu2=torch.rand(size,size,device=dev)

start=time.time()
torch.matmul(cpu1,cpu2)
last=time.time()
print(f"gpu time : {last-start:.2f}")

cpu time : 14.89
gpu time : 0.11


In [10]:
#reshaping and flattening
a

tensor([1, 2, 3], device='cuda:0')

In [13]:
k=torch.rand(4,4)

In [15]:
k.reshape(2,2,2,2)

tensor([[[[0.3622, 0.7451],
          [0.6292, 0.1474]],

         [[0.3509, 0.4153],
          [0.1728, 0.4643]]],


        [[[0.0237, 0.6885],
          [0.4193, 0.4174]],

         [[0.3666, 0.8745],
          [0.0038, 0.2817]]]])

In [16]:
k.flatten()

tensor([0.3622, 0.7451, 0.6292, 0.1474, 0.3509, 0.4153, 0.1728, 0.4643, 0.0237,
        0.6885, 0.4193, 0.4174, 0.3666, 0.8745, 0.0038, 0.2817])

In [18]:
k.permute(1,0)

tensor([[0.3622, 0.3509, 0.0237, 0.3666],
        [0.7451, 0.4153, 0.6885, 0.8745],
        [0.6292, 0.1728, 0.4193, 0.0038],
        [0.1474, 0.4643, 0.4174, 0.2817]])

In [21]:
r=torch.rand(256,256,3)
r.unsqueeze(0).shape

torch.Size([1, 256, 256, 3])

In [26]:
r.squeeze(1).shape

torch.Size([256, 256, 3])